### PR TITLE
fix the responsiveness.

### PR DESCRIPTION
**Pull request by Chayandev**
### Fixed Issue no:- #3 

Fixed the responsiveness issue as described in the issue #3 .

**width range (341px - 453px)**
Screenshot 2023-10-07 221146

Next

Screenshot 2023-10-07 221046

### CODE REVIEW

**Comment by nishitxmehta** [comment]
@Chayandev, there's minute change remaining in the responsiveness. 
In the width range `576px - 1150px`, the buttons text `Contact Me` and `Download Resume` comes in next line. Make both the buttons text in **single line** only. Below is the image for reference: 

Screenshot

**Comment by Chayandev** [comment]
Can u give me the SS of this portion where the text getting distorted mans
having line breaks.

**Comment by Chayandev** [comment]
ok working on that.

**Comment by nishitxmehta** [comment]
width (576px)
Screenshot (987)

width (1150px)
Screenshot (990)

The buttons should look like for range (576px - 1150px)
Screenshot

**Comment by Chayandev** [comment]
@nishitxmehta now it is fixed, please verify it.

**Pull request merged**
